[phases.setup]
nixPkgs = ['nodejs_20', 'yarn']

[phases.install]
cmds = ['NODE_ENV=development yarn install']

[phases.build]
cmds = ['NODE_ENV=production yarn build']

[start]
cmd = 'NODE_ENV=production yarn start'

[variables]
HOST = '0.0.0.0'
PORT = '1337'
